{
 "title": "Iot Datos Historicos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Humedad Actual",
   "type": "gauge",
   "description": "Gráfico gauge que mide respecto a un máximo y mínimo histórico el último valor recibido de humedad ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select b.\"Medicion\" as value\r\nfrom \"iotHistorico\" b\r\nwhere b.\"Variable\" = 'humedad'and (b.\"Usuario\" = '${__user.login}' or '${__user.login}' = 'admin')\r\norder by b.\"Fecha\" asc"
    }
   ]
  },
  {
   "title": "Temperatura actual",
   "type": "gauge",
   "description": "Gráfico gauge que mide respecto a un máximo y mínimo histórico el último valor recibido de temperatura",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select b.\"Medicion\" as value\nfrom \"iotHistorico\" b\nwhere b.\"Variable\" = 'temperatura' and (b.\"Usuario\" = '${__user.login}' or '${__user.login}' = 'admin')\norder by b.\"Fecha\" asc\n"
    }
   ]
  },
  {
   "title": "Humedad a través del tiempo",
   "type": "graph",
   "description": "Gráfica que muestra el comportamiento de humedad y temperatura a través del tiempo, mostrando las últimas 100 muestras",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"Fecha\"),\n  \"Variable\" AS metric,\n  \"Medicion\"\nFROM \"iotHistorico\"\nWHERE\n  \"Variable\" = 'humedad' and (\"Usuario\" = '${__user.login}' or '${__user.login}' = 'admin')\nORDER BY \"Fecha\" asc\nlimit 100"
    }
   ]
  },
  {
   "title": "Temperatura a través del tiempo",
   "type": "graph",
   "description": "Gráfica que muestra el comportamiento de humedad y temperatura a través del tiempo, mostrando las últimas 100 muestras",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   $__time(\"Fecha\"),\n  \"Variable\" AS metric,\n  \"Medicion\"\nFROM \"iotHistorico\"\nWHERE\n  \"Variable\" = 'temperatura' and (\"Usuario\" = '${__user.login}' or '${__user.login}' = 'admin')\nORDER BY \"Fecha\" asc\nlimit 100\n"
    }
   ]
  },
  {
   "title": "Humedad promedio y número de nodos por ciudad",
   "type": "geomap",
   "description": "Mapa que permite visualizar la información de los nodos y la humedad\nTamaño representa la cantidad de nodos tomando información en ese punto\nColor representa el valor de la humedad respecto a los máximos y mínimos definidos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select  c.\"numusuarios\", b.*, ciu.\"lat\" as latitude , ciu.\"lng\" as longitude\r\n\tfrom \"ciudades\" ciu\r\n\tinner join (select avg(iot.\"Medicion\") as temperatura, iot.\"Ciudad\"\r\n\tfrom \"iotHistorico\" iot\r\n\tinner join \"ciudades\" ciu on lower(iot.\"Ciudad\") = lower(ciu.city)\r\n\twhere iot.\"Variable\" = 'humedad'\r\n\tgroup by iot.\"Ciudad\" ) b on ciu.\"city\" = b.\"Ciudad\"\r\n\tinner join (select count(distinct(\"Usuario\")) as numUsuarios, \"Ciudad\" from \"iotHistorico\" group by \"Ciudad\")\r\n\tc on ciu.\"city\" = c.\"Ciudad\""
    }
   ]
  },
  {
   "title": "Temperatura promedio y número de nodos por ciudad",
   "type": "geomap",
   "description": "Mapa que permite visualizar la información de los nodos y la temperatura\nTamaño representa la cantidad de nodos tomando información en ese punto\nColor representa el valor de la temperatura respecto a los máximos y mínimos definidos",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select  c.\"numusuarios\", b.*, ciu.\"lat\" as latitude , ciu.\"lng\" as longitude\r\n\tfrom \"ciudades\" ciu\r\n\tinner join (select avg(iot.\"Medicion\") as temperatura, iot.\"Ciudad\"\r\n\tfrom \"iotHistorico\" iot\r\n\tinner join \"ciudades\" ciu on lower(iot.\"Ciudad\") = lower(ciu.city)\r\n\twhere iot.\"Variable\" = 'temperatura'\r\n\tgroup by iot.\"Ciudad\" ) b on ciu.\"city\" = b.\"Ciudad\"\r\n\tinner join (select count(distinct(\"Usuario\")) as numUsuarios, \"Ciudad\" from \"iotHistorico\" group by \"Ciudad\")\r\n\tc on ciu.\"city\" = c.\"Ciudad\""
    }
   ]
  },
  {
   "title": "Distribución de nodos por ciudad",
   "type": "piechart",
   "description": "Gráfico que muestra la distribución de nodos receptores de información por ciudad",
   "gridPos": { "h": 9, "w": 12, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nselect  count(distinct(b.\"Usuario\")) as value, INITCAP(REPLACE(b.\"Ciudad\", '_',' '))\r\nfrom \"iotHistorico\" b\r\ngroup by b.\"Ciudad\""
    }
   ]
  }
 ]
}